fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    concat:
      repo: puppetlabs/concat
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    epel:
      repo: puppet/epel
  symlinks:
    powerman: "#{source_dir}"
