fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
  symlinks:
    powerman: "#{source_dir}"
