---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el8
      - el9
      - el10
      - debian-11
      - debian-12
      - ubuntu-2204
      - ubuntu-2404
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
